# Generated by Django 4.1.1 on 2023-01-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jenis", models.CharField(max_length=75)),
                ("deskripsi", models.CharField(max_length=750)),
                (
                    "gambar",
                    models.ImageField(blank=True, null=True, upload_to="image/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Penangkaran",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_tempat", models.CharField(max_length=75)),
                ("grs_lintang", models.FloatField(null=True)),
                ("grs_bujur", models.FloatField(null=True)),
            ],
        ),
    ]
